development:
  adapter: async

test:
  adapter: test

production:
  <% enable_redis = %w[1 true yes].include?(ENV["ENABLE_REDIS"].to_s.downcase) && ENV["REDIS_URL"].to_s != "" %>
  adapter: <%= enable_redis ? "redis" : "async" %>
  <% if enable_redis %>
  url: <%= ENV["REDIS_URL"] %>
  <% end %>
  channel_prefix: coffee_production
